### ISSUE TITLE
Upload of custom .h5p file throws error

### ISSUE THREAD

**Issue by numismae** [Tuurlijk/t3ext-h5p#11]
Typo3 V9.5.14, Fix "h5p file upload by adding missing slash" #10 installed.

The Fix allows the upload of one initial .h5p file. However the uploaded .h5p content cannot be located in H5P section "All H5P content". Trying to upload of additional .h5p file throws the following error:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1423347324: Folder "h5p/editor/H5P.Transition-1.0" already exists.

**Comment by simon-kloker** [comment]
In Typo3 10.4.18 the upload is first blocked by forbidden filetypes (.j_). When this is fixed, it has problems with locating the libraries... Haven't found a workaround here yet...

**Comment by Tuurlijk** [comment]
Is this still an issue?

Uploading in the 'add element' module works for me:
![image](https://user-images.githubusercontent.com/790979/158057922-1c0acd66-8b96-4b67-a673-d9347d968b45.png)
