### ISSUE TITLE
An index with name 'content' was already defined on table 'tx_h5p_domain_model_contentresult'.

### ISSUE THREAD

**Issue by pixelplumber** [Tuurlijk/t3ext-h5p#2]
Hello, I've just tried installing this extension via composer.  When activating the extension in extension manager I receive the exception: 
```
(1/1) #60 Doctrine\DBAL\Schema\SchemaException
An index with name 'content' was already defined on table 'tx_h5p_domain_model_contentresult'.
```
I'm not a programmer but it looks to me like it is getting caught up loading the ext_tables.sql maybe on line 100/101.  
https://github.com/Tuurlijk/t3ext-h5p/blob/23f3bb04128242841fb9b2a0981115f92daf90c8/ext_tables.sql#L100
https://github.com/Tuurlijk/t3ext-h5p/blob/23f3bb04128242841fb9b2a0981115f92daf90c8/ext_tables.sql#L101
Is the issue that the same index name is used twice?
Kind regards,
Mark.

**Comment by Tuurlijk** [comment]
Thx. Should be fixed since https://github.com/Tuurlijk/t3ext-h5p/tree/v0.2.4
