### ISSUE TITLE
TYPO3 error on copy & paste

### ISSUE THREAD

**Issue by AstCommodore** [Tuurlijk/t3ext-h5p#26]
If you copy & paste a normal content element, TYPO3 throws an error in case of pasting it:

2: SQL error: 'Incorrect integer value: '' for column 'tx_h5p_content' at row 1'

TCA and SQL definitions lock well - I don't know where the bugs might hide.

**Comment by AstCommodore** [comment]
It's easy to fix, please add `'default' => '0',` to TCA config of field `tx_h5p_content`

**Comment by Tuurlijk** [comment]
Fixed in all branches. Will be in next release
