### ISSUE TITLE
Typo3 Version 11

### ISSUE THREAD

**Issue by numismae** [Tuurlijk/t3ext-h5p#27]
Hi, are there any plans to update the extension for version 11, release date etc? Thank you

**Comment by christophrunkel** [comment]
I would also be interested in a Typo3 11 compatible version and would sponsor that.

**Comment by ErichManser** [comment]
We are interested as well in a TYPO3 v11 version and would sponsor as well!

**Comment by Tuurlijk** [comment]
It's out. Please let me know if everything works.
