### ISSUE TITLE
Error on try to edit/create specific Content Types like Interactive Video or Drag & Drop

### ISSUE THREAD

**Issue by numismae** [Tuurlijk/t3ext-h5p#29]
Typo3 Administration Log:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function getUid() on null | Error thrown in file .../public/typo3conf/ext/h5p/Classes/Domain/Repository/LibraryTranslationRepository.php in line 46. 

Console: 
https://.../typo3/index.php?route=%2Fh5p%2Feditor%2Faction&token=d0d87ea2caffadf75776bc4c3b3af545a6736fb6&action=h5p_libraries&machineName=H5P.InteractiveVideo&majorVersion=1&minorVersion=22&language=en
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (index.php, line 0)

Typo3 Version 10.4.21
H5P Extension Version 10.0.10

**Comment by Tuurlijk** [comment]
Please try 10.0.13 to see if that fixes the issue

**Comment by numismae** [comment]
that fixed it, thank you
