### ISSUE TITLE
Error when trying to edit an existing record

### ISSUE THREAD

**Issue by michael-binder** [Tuurlijk/t3ext-h5p#5]
I get an error 'Column 'license_version' cannot be null' by trying to edit an existing record.
Can you reproduce that, or do I have a misconfiguration?

Fresh and blank TYPO3 9.5.10 ddev installation.

**Comment by Holger273** [comment]
Same issue here (TYPO3 10.4.9). What have I done wrong.

**Comment by potofcoffee** [comment]
Same issue here.
Quick workaround (this should be fixed, however): Next to "Title", click on the meta data button and fill in license and license version info.

**Comment by Tuurlijk** [comment]
Should be fixed in coming releases
