### ISSUE TITLE
h5p Upload

### ISSUE THREAD

**Issue by manuelportela** [Tuurlijk/t3ext-h5p#6]
Environment: ddev TYPO3 composer install @9.5.11,  t3ext-h5p @0.2.15

Unable to upload existing .h5p

Throws: TYPO3\CMS\Core\Resource\Exception\ExistingTargetFolderException
if wrapped in catch/try next error is "Error while fetching permissions for /var/www/html/public/fileadmin/h5p/editorH5PEditor.InteractiveVideo-1.17/images"

Is T3v9 broken? Have not tried earlier versions.

Thank you for hinting me the way

**Comment by astehlik** [comment]
@manuelportela I had the same problem and fixed it in pull request #10

Please check it out if it solves the problem for you as well.

**Comment by Tuurlijk** [comment]
Close because a lack of feedback. It works for me in v10
