### ISSUE TITLE
The file you are trying to upload might be too large.

### ISSUE THREAD

**Issue by falscher20er** [Tuurlijk/t3ext-h5p#9]
Hello,

thanks for your Work to H5P and Typo3!

Every time I try to upload a graphic I get an error message that the file is too large: The file you are trying to upload might be too large.
Upload in PHP is set to 128MB. The graphics range from 100 - 1000kb. Fileupload in Typo3 is possible. 

Best regards
Matthias

**Comment by Holger273** [comment]
Same issue here on Typo3 9.5.15:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Core\Utility\File\ExtendedFileUtility::init() | Error thrown in file /xxx/xxx/typo3/public/typo3conf/ext/h5p/Classes/Adapter/Core/FileStorage.php in line 465. Requested URL: https://xxx/typo3/index.php?route=%%2Fh5p%%2Feditor%%2Faction&token=--AnonymizedToken--&action=h5p_files

**Comment by horstmue** [comment]
Hello,

remove or comment out the line 

`$fileProcessor->init([], []);`

in function "savefile" in typo3conf/ext/h5p/Classes/Adapter/Core/FileStorage.php

The init function was removed on newer TYPO3 Versions.

Hope this helps
Horst

**Comment by Tuurlijk** [comment]
This should be fixed in coming releases
